name: Docker Build and Push

on:
  repository_dispatch:
    types: [publish-docker]
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to tag (leave empty for latest)'
        required: false
        type: string

jobs:
  ci:
    name: CI Checks
    uses: ./.github/workflows/ci.yml

  docker:
    name: Build and Push Docker Image
    needs: ci
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get version
        id: get_version
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            VERSION="${{ inputs.version }}"
          else
            VERSION="${{ github.event.client_payload.version }}"
          fi
          if [ -z "$VERSION" ]; then
            VERSION=$(node -p "require('./package.json').version")
          fi
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/clubs:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/clubs:v${{ steps.get_version.outputs.VERSION }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
